import type {Metadata} from "next";
import {Nunito} from "next/font/google";
import {ClerkProvider} from "@clerk/nextjs";
import {Toaster} from "@/components/ui/sonner";
import "./globals.css";
import {ThemeProvider} from "@/components/theme-provider";
import ExitModal from "@/components/modals/exit-modal";
import HeartsModal from "@/components/modals/hearts-modal";
import PracticeModal from "@/components/modals/practice-modal";

const defFont = Nunito({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
            <body className={defFont.className}>
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
            >
                <Toaster/>
                <ExitModal/>
                <HeartsModal/>
                <PracticeModal/>
                {children}
            </ThemeProvider>
            </body>
            </html>
        </ClerkProvider>
    );
}
